#!/usr/bin/env bash
#
# @(#)lab 0.0.1
# @(#)(c) 2020 redpeacock78
# @(#)MIT License is applied to this script.
# @(#)
########################################
# @(#)Derives the color difference using the method defined by LAB Delta E (CIE76, CIE94, CIEDE2000).
# @(#)Arguments:
# @(#)  -dE76
# @(#)  -dE84 [-g, -t]
# @(#)  -dE00
# @(#)  -v, --version
# @(#)  -h, --help
# @(#)Returns:
# @(#)  None
# @(#)Depends:
# @(#)  SHIFT
# @(#)  BASH
# @(#)  ECHO
# @(#)  AWK
# @(#)  SED
# @(#)  CAT
# @(#)  BC
########################################

####MESSAGES####
###VERSION###
function version() {
    {
        cat <<EOS
${0##*/} 0.0.1
Copyright (C) 2019 redpeacock78
License MIT.
THIS IS FREE SOFTWARE.
YOU ARE FREE TO CHANGE AND REDISTRIBUTE IT.
THERE IS NO WARRANTY, TO THE EXTENT PERMITTED BY LAW.
Written by redpeacock78 <https://github.com/redpeacock78>.
EOS
        exit 0
    }
}
###SHOW_USAGE###
function usage() {
    {
        cat <<EOS >&2
Usage: ${0##*/} [OPTION] L1 a1 b1 L2 a2 b2

Derives the color difference using the method defined
by LAB Delta E (CIE76, CIE94, CIEDE2000).

Option:
  -dE76            Use the CIE 1976 color difference formula.
  -dE94 [-g, -t]   Use the CIE 1994 color difference formula.
                   (-g: kl=1,k1=0.045,k2=0.015 / -t: kl=2,k1=0.048,k2=0,014)
  -dE00            Use the CIEDE2000 color difference formula.
  -v, --version    Show version and info.
  -h, --help       Show usage.

TL;DR
  $ ${0##*/} -dE76 '50 50 0 40 50 0'
  $ ${0##*/} -dE94 -g '50 50 0 40 50 0'
  $ ${0##*/} -dE00 '50 50 0 40 50 0'
EOS
        exit 0
    }
}
###ERROR_MESSAGE###
function error() {
    {
        cat <<ERR 1>&2
${0##*/}: Sorry. An error has occurred :_(
Refer '${0##*/} -h' or '${0##*/} --help' for how to use the command.
ERR
        exit 1
    }
}

####MAIN_PROCESSING####
function calc() {
    {
        BC_LINE_LENGTH=999 bc -l <<<"scale=100; ${@}" | sed 's/^\./0./;s/^-\./-0./'
    }
}
function dE76() {
    #Reference: https://ja.wikipedia.org/wiki/%E8%89%B2%E5%B7%AE#CIE76_(delta_E76)
    {
        #* 基準色
        declare La=${@:1:1}
        declare aa=${@:2:1}
        declare ba=${@:3:1}

        #* 比較色
        declare Lb=${@:4:1}
        declare ab=${@:5:1}
        declare bb=${@:6:1}

        declare Lab=$(calc "(${Lb/L*=/} - ${La/L*=/}) ^ 2")
        declare aab=$(calc "(${ab/a*=/} - ${aa/a*=/}) ^ 2")
        declare bab=$(calc "(${bb/b*=/} - ${ba/b*=/}) ^ 2")

        calc "sqrt(${Lab} + ${aab} + ${bab})"
    }
}
function dE94() {
    #Reference: https://ja.wikipedia.org/wiki/%E8%89%B2%E5%B7%AE#CIE94_(delta_E94)
    {
        declare k=${@:1:1}
        shift

        #* 重み付け係数
        declare kc="1"
        declare kh="1"
        if [[ "${k}" == "-g" ]]; then
            declare kl="1"
            declare k1="0.045"
            declare k2="0.015"
        elif [[ "${k}" == "-t" ]]; then
            declare kl="2"
            declare k1="0.048"
            declare k2="0.014"
        elif [[ -z "${k}" ]] ||
            [[ "${k}" != "-g" ]] ||
            [[ "${k}" != "-t" ]]; then
            error
        fi

        #* 基準色
        declare L1=${@:1:1}
        declare a1=${@:2:1}
        declare b1=${@:3:1}

        #* 比較色
        declare L2=${@:4:1}
        declare a2=${@:5:1}
        declare b2=${@:6:1}

        declare delta_L=$(calc "(${L1/L*=/} - ${L2/L*=/})")

        declare c1=$(calc "sqrt((${a1/a*=/} ^ 2) + (${b1/b*=/} ^ 2))")
        declare c2=$(calc "sqrt((${a2/a*=/} ^ 2) + (${b2/b*=/} ^ 2))")
        declare delta_cab=$(calc "${c1} - ${c2}")

        declare delta_a=$(calc "(${a1/a*=/} - ${a2/a*=/})")
        declare delta_b=$(calc "(${b1/b*=/} - ${b2/b*=/})")

        declare delta_hab=$(calc "sqrt((${delta_a} ^ 2) + (${delta_b} ^ 2) - (${delta_cab} ^ 2))")

        declare sl="1"
        declare sc=$(calc "(1 + (${k1} * ${c1}))")
        declare sh=$(calc "(1 + (${k2} * ${c1}))")

        declare a=$(calc "((${delta_L}/(${kl} * ${sl})) ^ 2)")
        declare b=$(calc "((${delta_cab}/(${kc} * ${sc})) ^ 2)")
        declare c=$(calc "((${delta_hab}/(${kh} * ${sh})) ^ 2)")

        calc "sqrt(${a} + ${b} + ${c})"
    }
}
function dE00() {
    #Reference: https://ja.wikipedia.org/wiki/%E8%89%B2%E5%B7%AE#CIEDE2000_(delta_E00)
    {
        function abs() {
            {
                awk '{OFMT="%.100f"}{print abs($1)} function abs(x){return (x < 0)?-x:x}' <<<"${@}"
            }
        }
        function exp() {
            {
                awk '{OFMT="%.100f"}{print exp($1)}' <<<"${@}"
            }
        }
        function atan2() {
            {
                awk '{OFMT="%.100f"}{print atan2($1, $2)}' <<<"${@}"
            }
        }
        function radian2degree() {
            {
                calc "${@} * (180 / ${pi})"
            }
        }
        function degree2radian() {
            {
                calc "${@} * (${pi} / 180)"
            }
        }

        declare pi=$(calc "4 * a(1)")

        #* 加重係数
        declare kl="1"
        declare kc="1"
        declare kh="1"

        #* 基準色
        declare L1=${@:1:1}
        declare a1=${@:2:1}
        declare b1=${@:3:1}

        #* 比較色
        declare L2=${@:4:1}
        declare a2=${@:5:1}
        declare b2=${@:6:1}

        declare delta_Lp=$(calc "${L2/L*=/} - ${L1/L*=/}")

        declare L_=$(calc "(${L1/L*=/} + ${L2/L*=/}) / 2")

        declare c1=$(calc "sqrt((${a1/a*=/} ^ 2) + (${b1/b*=/} ^ 2))")
        declare c2=$(calc "sqrt((${a2/a*=/} ^ 2) + (${b2/b*=/} ^ 2))")
        declare c_=$(calc "(${c1} + ${c2}) / 2")

        declare ap1=$(
            calc \
                "${a1/a*=/} + (${a1/a*=/} / 2) * \
                (1 - sqrt( \
                    (${c_} ^ 7) / \
                    ((${c_} ^ 7) + (25 ^ 7)) \
                ))"
        )
        declare ap2=$(
            calc \
                "${a2/a*=/} + (${a2/a*=/} / 2) * \
                (1 - sqrt( \
                    (${c_} ^ 7) / \
                    ((${c_} ^ 7) + (25 ^ 7)) \
                ))"
        )

        declare cp1=$(calc "sqrt((${ap1} ^ 2) + (${b1/b*=/} ^ 2))")
        declare cp2=$(calc "sqrt((${ap2} ^ 2) + (${b2/b*=/} ^ 2))")
        declare cp_=$(calc "(${cp1} + ${cp2}) / 2")
        declare delta_cp=$(calc "${cp2} - ${cp1}")

        if [[ $(calc "${b1/b*=/} == 0") == 1 ]] && [[ $(calc "${ap1} == 0") == 1 ]]; then
            declare hp1="0"
        else
            declare hp1=$(
                radian2degree $(
                    atan2 ${b1/b*=/} ${ap1}
                )
            )
            if [[ $(calc "${hp1} < 0") == 1 ]]; then
                declare hp1=$(calc "${hp1} + 360")
            fi
        fi
        if [[ $(calc "${b2/b*=/} == 0") == 1 ]] && [[ $(calc "${ap2} == 0") == 1 ]]; then
            declare hp2="0"
        else
            declare hp2=$(
                radian2degree $(
                    atan2 ${b2/b*=/} ${ap2}
                )
            )
            if [[ $(calc "${hp2} < 0") == 1 ]]; then
                declare hp2=$(calc "${hp2} + 360")
            fi
        fi

        declare abs=$(abs $(
            calc "${hp1} - ${hp2}"
        ))

        if [[ $(calc "${c1} == 0") == 1 ]] || [[ $(calc "${c2} == 0") == 1 ]]; then
            declare delta_hp1="0"
        elif [[ $(calc "${abs} <= 180") == 1 ]]; then
            declare delta_hp1=$(calc "${hp2} - ${hp1}")
        elif [[ $(calc "${hp2} <= ${hp1}") == 1 ]]; then
            declare delta_hp1=$(calc "${hp2} - ${hp1} + 360")
        else
            declare delta_hp1=$(calc "${hp2} - ${hp1} - 360")
        fi

        declare delta_hp=$(calc "2 * sqrt(${cp1} * ${cp2}) * s($(degree2radian ${delta_hp1}) / 2)")

        if [[ $(calc "${abs} > 180") == 1 ]]; then
            declare hp_=$(calc "(${hp1} + ${hp2} + 360) / 2")
        else
            declare hp_=$(calc "(${hp1} + ${hp2}) / 2")
        fi

        declare t_a=$(
            degree2radian $(
                calc "${hp_} - 30"
            )
        )
        declare t_b=$(
            degree2radian $(
                calc "2 * ${hp_}"
            )
        )
        declare t_c=$(
            degree2radian $(
                calc "3 * ${hp_} + 6"
            )
        )
        declare t_d=$(
            degree2radian $(
                calc "4 * ${hp_} - 63"
            )
        )
        declare t=$(
            calc \
                "1 - \
                (0.17 * c(${t_a})) + \
                (0.24 * c(${t_b})) + \
                (0.32 * c(${t_c})) - \
                (0.20 * c(${t_d}))"
        )

        declare sl=$(
            calc \
                "1 + ( \
                    0.015 * (((${L_} - 50) ^ 2) / \
                    sqrt(20 + (${L_} - 50) ^ 2)) \
                )"
        )
        declare sc=$(calc "1 + 0.045 * ${cp_}")
        declare sh=$(calc "1 + 0.015 * ${cp_} * ${t}")

        declare exp_hp_=$(
            exp $(
                calc "-(((${hp_} - 275) / 25) ^ 2)"
            )
        )
        declare radian_exp_hp_=$(
            degree2radian $(
                calc "60 * ${exp_hp_}"
            )
        )
        declare rt=$(
            calc \
                "-2 * \
                sqrt( \
                    (${cp_} ^ 7) / \
                    ((${cp_} ^ 7) + (25 ^ 7)) \
                ) * \
                s( \
                    ${radian_exp_hp_} \
                )"
        )

        calc \
            "sqrt( \
                ((${delta_Lp}/(${kl} * ${sl})) ^ 2) + \
                ((${delta_cp}/(${kc} * ${sc})) ^ 2) + \
                ((${delta_hp}/(${kh} * ${sh})) ^ 2) + \
                ${rt} * (${delta_cp}/(${kc} * ${sc})) * (${delta_hp}/(${kh} * ${sh})) \
            )"
    }
}

if [[ ${@:1:1} == "-dE76" ]]; then
    shift &&
        dE76 ${@} | awk '{printf("%.4f\n",$1)}'
elif [[ ${@:1:1} == "-dE94" ]]; then
    shift &&
        dE94 ${@} | awk '{printf("%.4f\n",$1)}'
elif [[ ${@:1:1} == "-dE00" ]]; then
    shift &&
        dE00 ${@} | awk '{printf("%.4f\n",$1)}'
elif [[ ${@:1:1} == "-v" ]] ||
    [[ ${@:1:1} == "--version" ]]; then
    version
elif [[ ${@:1:1} == "-h" ]] ||
    [[ ${@:1:1} == "--help" ]]; then
    usage
elif [[ -z ${@:1:1} ]] ||
    [[ ${@:1:1} != "-h" ]] ||
    [[ ${@:1:1} != "--help" ]]
    [[ ${@:1:1} != "-v" ]] ||
    [[ ${@:1:1} != "--version" ]] ||
    [[ ${@:1:1} != "-dE76" ]] ||
    [[ ${@:1:1} != "-dE94" ]] ||
    [[ ${@:1:1} != "-dE00" ]]; then
    error
fi
