#!/usr/bin/env bash

declare abs_path="$(builtin cd "$(dirname ${0})" && builtin pwd)"
source "${abs_path%/*}/libexec/lab-error"

function judge() {
    [[ "${#@}" != 6 ]] && error
    {
        declare test_a=${@:1:1}
        declare test_b=${@:2:1}
        declare test_c=${@:3:1}
        declare test_d=${@:4:1}
        declare test_e=${@:5:1}
        declare test_f=${@:6:1}

        declare test_all=$(
            echo ${test_a/L*=/} ${test_b/a*=/} ${test_c/b*=/} ${test_d/L*=/} ${test_e/a*=/} ${test_f/b*=/}
        )

        echo ${test_all} |
            tr ' ' \\n |
            xargs -n1 -I{} sh -c 'grep -q "^-\?[0-9]\+\.\?[0-9]*$" <<<"{}"'
    } || error
}
