name: build

on:
  push:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Setup
        run: |
          sudo add-apt-repository ppa:duggan/bats
          sudo apt-get update
          sudo apt-get install bats
      - name: Run Test
        run: |
          bats test/*
      - name: install CIE.sh
        run:
          sudo ./install.sh ${PREFIX:-/usr/local}
      - name: Show version
        run: |
          lab --version
      - name: Show help
        run: |
          lab --help
      - name: Run
        run: |
          lab -dE76 50 50 0 40 50 0
          lab -dE94 -g 50 50 0 40 50 0 
          lab -dE94 -t 50 50 0 40 50 0
          lab -dE00 50 50 0 40 50 0